DEBUG:pymongo.connection:{"clientId": {"$oid": "66a7e6fab2558d8721413f19"}, "message": "Connection pool created", "serverHost": "localhost", "serverPort": 27017}
DEBUG:root:passed line 13 btw
DEBUG:pymongo.serverSelection:{"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66a7e6fab2558d8721413f19, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66a7e6fab2558d8721413f19"}}
DEBUG:pymongo.serverSelection:{"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66a7e6fab2558d8721413f19, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66a7e6fab2558d8721413f19"}, "remainingTimeMS": 29}
DEBUG:pymongo.serverSelection:{"message": "Server selection failed", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66a7e6fab2558d8721413f19, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>", "clientId": {"$oid": "66a7e6fab2558d8721413f19"}, "failure": "\"localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\""}
